{"name": "test_delete_vpc", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 204", "trace": "self = <pytest_case.vpc.test_vpc_vpc.Test_Vpc object at 0x000002081FB85548>\n\n    def test_delete_vpc(self):\n        res = Vpc().delete_vpc(token,project_id, vpc_id)\n>       assert res.status_code == 204\nE       assert 404 == 204\n\ntest_vpc_vpc.py:68: AssertionError"}, "start": 1627346985896, "stop": 1627346987349, "uuid": "d53649f6-5c92-4fad-9297-3eb361701a3d", "historyId": "d9a5c448be2594643c77ec807bee5ee1", "testCaseId": "a4f0a201ccdcf8ee08d84f9df9e2c3b7", "fullName": "pytest_case.vpc.test_vpc_vpc.Test_Vpc#test_delete_vpc", "labels": [{"name": "parentSuite", "value": "pytest_case.vpc"}, {"name": "suite", "value": "test_vpc_vpc"}, {"name": "subSuite", "value": "Test_Vpc"}, {"name": "host", "value": "no-delecs-g42-test-wx405299"}, {"name": "thread", "value": "5588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_case.vpc.test_vpc_vpc"}]}